PR to main from Landing Page
RateMyContractors/rate_my_contractor pull request #2
Opened 2024-10-12 19:51 UTC by inikasingh21

Created Landing Page

2024-10-14 15:28 UTC, erickjtorres requested changes
Looks good so far nice work! Just had a couple of nit comments. 

@bridgettorres @inikasingh21 please remove any unnecessary comments or try to avoid any commented code in the future. It makes it harder to read the code

2024-10-14 15:28 UTC, erickjtorres commented on lib/main.dart
> +                      //     Navigator.push(
remove unnecessary comments

2024-10-14 15:28 UTC, erickjtorres commented on lib/main.dart
> +                          searchQuery = value; //user input being assigned as recieved
don't need this comment

2024-10-14 15:28 UTC, erickjtorres commented on lib/main.dart
> +                        //shape: RoundedRectangleBorder(
unnecessary

2024-10-14 15:28 UTC, erickjtorres commented on lib/main.dart
> +  get child => null; //user input
I don't think you need this what is this used for?

2024-10-16 21:29 UTC, erickjtorres approved these changes

2024-10-17 04:11 UTC, bridgettorres reviewed
LGTM

2024-10-17 04:11 UTC, bridgettorres commented on pubspec.yaml
>    #   - images/a_dot_burr.jpeg
Remove unneeded dependencies

2024-10-17 04:13 UTC, bridgettorres approved these changes

2024-10-19 15:47 UTC, merged