Feature/contractor card
RateMyContractors/rate_my_contractor pull request #3
Opened 2024-10-22 18:46 UTC by inikasingh21

![image](https://github.com/user-attachments/assets/d4f6b451-6091-468e-b52f-ae7404582aba)
![image](https://github.com/user-attachments/assets/a66215d5-f686-4d9c-801a-88f62557c90e)

2024-10-22 21:59 UTC, erickjtorres approved these changes

2024-10-22 21:59 UTC, erickjtorres commented on lib/main.dart
> +      //home: const ContractorPage(),
remove this comment please

2024-10-22 21:59 UTC, erickjtorres commented on lib/widgets/c_card_widget.dart
Can you update the name of this. Should match the name of the class (ie: contractor_card.dart)

2024-10-22 21:59 UTC, erickjtorres commented on lib/results_page.dart
> +  const ResultsPage({super.key}); //constructor for creating the class (when creating a new object from the class the cunstroctor is automatically called to initialize it in which the constructor is
nit. Please remove these comments

2024-10-22 21:59 UTC, erickjtorres commented on lib/results_page.dart
> +class OvalTags extends StatelessWidget {
did we not move this to another page already? Might just need to merge the other branch and these changes will update

2024-10-22 22:00 UTC, erickjtorres requested changes
just some small changes requested. Nice work!

2024-10-24 00:10 UTC, erickjtorres approved these changes

2024-10-30 22:32 UTC, bridgettorres approved these changes

2024-11-07 04:56 UTC, merged