feat: added initial work for login
RateMyContractors/rate_my_contractor pull request #7
Opened 2024-12-08 20:14 UTC by erickjtorres

2024-12-10 06:06 UTC, bridgettorres commented on lib/authentication/login/models/email.dart
> +  EmailValidationError? validator(String value) {
Here we are checking whether the input is empty however we should consider the edge case of an invalid input where the user does not include the @ symbol

2024-12-10 06:06 UTC, bridgettorres commented on lib/authentication/login/models/password.dart
> +  PasswordValidationError? validator(String value) {
Lets also consider password length validation. Users shouldn't be able to use one character as their password

2024-12-10 06:06 UTC, bridgettorres commented on lib/authentication/login/widgets/login_form.dart
> +    return TextField(
could we add a placeholder hint text field

2024-12-10 06:06 UTC, inikasingh21 requested changes

2024-12-10 06:06 UTC, inikasingh21 commented on lib/authentication/login/bloc/login_bloc.dart
> +        isValid: Formz.validate([state.password, email]),
does it ignore the password's value here since we are checking if only the email is dirty?

2024-12-10 06:06 UTC, inikasingh21 commented on lib/main.dart
> +                                            BlocProvider.of<AuthenticationBloc>(
what is the purpose of passing the AuthenticationBloc when the user is not authenticated?

2024-12-10 06:06 UTC, inikasingh21 commented on lib/main.dart
> +                  AuthenticationSubscriptionRequested(),
What does this do?

2025-01-03 03:33 UTC, bridgettorres approved these changes

2025-01-03 03:51 UTC, inikasingh21 approved these changes

2025-01-03 05:43 UTC, merged