Feature/signupbloc
RateMyContractors/rate_my_contractor pull request #8
Opened 2024-12-29 22:40 UTC by inikasingh21

Implemented SignUp form allowing users to create accounts and login in using their credentials. Also added user information to Supabase Authentication. 
![image](https://github.com/user-attachments/assets/1255fdd3-3bad-4d73-ba86-19cb93fd7bf9)
sign up clickable text and login button is greyed out and the UI is changed
![image](https://github.com/user-attachments/assets/568f8232-5908-45e3-bb55-73a5fc560be6)
sign up can switch from user and contractor
![image](https://github.com/user-attachments/assets/0ab55e78-fed0-4669-b43e-b107b2106843)
specific errors should appear
![image](https://github.com/user-attachments/assets/fc721c52-19e6-42d2-a743-8171e5bd5d35)
different errors for specifications
![image](https://github.com/user-attachments/assets/1182f989-9ed3-4b4a-bc03-b1cd9faf98f4)
pop up for password suggestions
![image](https://github.com/user-attachments/assets/59c62d68-a9e6-4881-a260-1e2896211dcc)
snackbar should appear and so will a loading symbol and the page will not go into login until continue is pressed on the snackbar
![image](https://github.com/user-attachments/assets/19b41998-9ac4-4ca4-87e5-6e6a2d1824df)
once the user is logged in, the name will be displayed on the top right
![image](https://github.com/user-attachments/assets/5ccc7ba1-a4ce-4bd0-a89b-8b22afaf1c1d)
and the authenticated user can search through the search bar

2025-01-03 05:51 UTC, erickjtorres requested changes, later dismissed
just some nit changes

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/login/bloc/login_state.dart
> +//was trying to figure out how to pass the value that is being returned so like from login_bloc.dart line 60 how does this get passed to the state with success
was this already answered? If yes then can we remove this comment porfavor

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/login/models/user.dart
> +//import 'package:rate_my_contractor/authentication/login/models/user_dto.dart';
nit not needed

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/login/widgets/login_form.dart
> +          //   Navigator.push(context,
nit remove comment here

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/signup/models/email.dart
> +  String validationError(EmailValidationError error) {
lets keep this in the widget instead pls. The widget that uses this state should be deciding how to display the error message. We shouldn't be defining that here

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/signup/models/firstname.dart
> +  String validationError(FirstNameValidationError error) {
same here

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/signup/models/lastname.dart
> +  String validationError(LastNameValidationError error) {
same here

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/signup/models/password.dart
> +  String validationError(PasswordValidationError error) {
same here

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/signup/models/username.dart
> +  String validationError(UsernameValidationError error) {
same here

2025-01-03 05:51 UTC, erickjtorres commented on lib/authentication/signup/models/username.dart
> +    //check for uniqueness
unnessary comment

2025-01-03 05:51 UTC, erickjtorres commented on lib/main.dart
> +                              // builder: (_) => BlocProvider.value(
remove this commented code please

2025-01-03 05:51 UTC, erickjtorres commented on web_scraper/utils/const/chicago_scraper_constants.py
> +WINDOWS_DRIVER = "drivers/chromedriver.exe"
is this supposed to be here?

2025-01-03 06:39 UTC, erickjtorres commented
fyi: I added this packages and fixed some of the listing errors
https://pub.dev/packages/very_good_analysis

2025-01-04 21:21 UTC, bridgettorres commented on web_scraper/utils/const/chicago_scraper_constants.py
> +WINDOWS_DRIVER = "drivers/chromedriver.exe"
yes!

2025-01-06 00:50 UTC, bridgettorres submitted a review, later dismissed
LGTM!

2025-01-19 20:50 UTC, bridgettorres approved these changes
great work bridget and inika !

2025-01-21 21:01 UTC, erickjtorres approved these changes
LGTM! Nice work chat

2025-01-21 21:02 UTC, merged